USE dbms
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER FUNCTION dbo.check_string(
	@name varchar(100)
) 
RETURNS BIT
AS
BEGIN
	IF @name IS NULL
		RETURN 1
	IF LEN(@name) <= 1
		RETURN 0
	IF NOT SUBSTRING(@NAME,1,1) LIKE '%[A-Z]'COLLATE Latin1_General_CS_AS
		RETURN 0
	RETURN 1
END
